# Generated by Django 2.1.3 on 2018-11-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraficasApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='competenciasp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='competenciasq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='competenciast',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='escritop',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='escritoq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='escritot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='inglesp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='inglesq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='inglest',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lecturacriticap',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lecturacriticaq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lecturacriticat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='razonamientop',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='razonamientoq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='razonamientot',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
