# Generated by Django 2.1.3 on 2018-11-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraficasApp', '0002_auto_20181114_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='competenciase',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='escritoe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='inglese',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='lecturacriticae',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='razonamientoe',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
