# Generated by Django 2.1.3 on 2018-11-18 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GraficasApp', '0003_auto_20181114_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='escrito',
        ),
    ]
