# Generated by Django 2.1.3 on 2018-11-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraficasApp', '0004_remove_estudiante_escrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
