# Generated by Django 2.1.3 on 2018-11-18 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraficasApp', '0005_auto_20181118_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
