# Generated by Django 2.1.3 on 2018-11-20 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraficasApp', '0006_auto_20181118_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cientificoe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cientificop',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cientificoq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='cientificot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='diseñoe',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='diseñop',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='diseñoq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='diseñot',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='formulacione',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='formulacionp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='formulacionq',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='formulaciont',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
