# Generated by Django 2.1.3 on 2018-11-26 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraficasApp', '0011_auto_20181126_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='formulacionp',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(1)]),
        ),
    ]
