# Generated by Django 2.1.3 on 2018-11-27 04:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GraficasApp', '0017_auto_20181126_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='cientificoe',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cientificop',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cientificoq',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cientificot',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='competenciase',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='competenciasp',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='competenciasq',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='competenciast',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='diseñoe',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='diseñop',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='diseñoq',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='diseñot',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='escritoe',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='escritop',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='escritoq',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='escritot',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='formulacione',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='formulacionp',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='formulacionq',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='formulaciont',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='inglese',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='inglesp',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='inglesq',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='inglest',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lecturacriticae',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lecturacriticap',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lecturacriticaq',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='lecturacriticat',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='razonamientoe',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='razonamientop',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='razonamientoq',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='razonamientot',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(0)]),
        ),
    ]
